### ISSUE TITLE
Tracking not starting

### ISSUE THREAD

**Issue by sarabnoya** [azzhu/EasyFlyTracker#11]
Hi, 
Thanks for sharing this! It is great to have something so user friendly.
Now to the troubleshooting.
I am having a problem while running the first step. Once it finishes calculating the background it stops. 
I have tried with my videos but also with the demos and it always stops at the same step.
Any suggestions? 

Collect frames...Done
Calculate the background image...Done
Finished, time consuming:75.42416000366211s

**Comment by azzhu** [comment]
can you share your config.yaml file to me?

**Comment by sarabnoya** [comment]
Absolutely.
I am sending the config from the Demo36. Is the one I have used so far. In case this is of help, I am running it on a mac.
Somehow I can not upload the YAML file but I put it in a .txt format.
[Config_file_easyFlyTracker.txt](https://github.com/azzhu/EasyFlyTracker/files/14364739/Config_file_easyFlyTracker.txt)

**Comment by sarabnoya** [comment]
Following up on this issue. Any suggestions to make it work?

**Comment by Susuqu** [comment]
![image](https://github.com/azzhu/EasyFlyTracker/assets/38428774/24f4a822-8c9f-4827-806b-989a11215b0a)
You can change the parameter to True, and then try again.

**Comment by Susuqu** [comment]
> You can change the parameter to True, and then try again.

![image](https://github.com/azzhu/EasyFlyTracker/assets/38428774/e401d3d5-ed9f-43ae-a6d1-e656382a4d43)


> Following up on this issue. Any suggestions to make it work?

**Comment by Susuqu** [comment]
> Absolutely. I am sending the config from the Demo36. Is the one I have used so far. In case this is of help, I am running it on a Mac. Somehow I can not upload the YAML file but I put it in a .txt format. [Config_file_easyFlyTracker.txt](https://github.com/azzhu/EasyFlyTracker/files/14364739/Config_file_easyFlyTracker.txt)

You can change the parameter to "True" in the following picture, and try again
show track result: True


![image](https://github.com/azzhu/EasyFlyTracker/assets/38428774/0d67e662-9a54-4677-b89b-ed60d6859d54)

**Comment by sarabnoya** [comment]
Perfect!!
