### ISSUE TITLE
Segmentation Fault

### ISSUE THREAD

**Issue by mmit2928** [azzhu/EasyFlyTracker#5]
Hello. I am inexperienced with computer programming and python. I downloaded this program and am using in terminal macOS 12. I was successfully able to analyze the demo video last week but now I am getting a segmentation fault error message. Can you tell me why this is happening and how to fix it? 

The error message is:
saved config params to: /Users/mckenzie/Downloads/easyFlyTrackerConf/output/config.pkl
tracking...
zsh: segmentation fault  easyFlyTracker /Users/mckenzie/Downloads/easyFlyTrackerConf/config.yaml

I have attached images of the apple error message, my output folder, and the yaml file below. 
[apple error.txt](https://github.com/azzhu/EasyFlyTracker/files
<img width="1440" alt="yaml" src="https://user-images.git
<img width="746" alt="pic of file location" src="https://user-images.githubusercontent.com/120639093/207823257-76888b8b-ec9b-4bf4-9e06-1d66d3a46d38.png">
hubusercontent.com/120639093/207823232-b7a151ac-194c-405f-8ab6-07912348194a.png">
/10235656/apple.error.txt)
<img width="1440" alt="segmentation fault" src="https://user-images.githubusercontent.com/120639093/207823172-07d13d1d-41f6-4e95-a269-8c79e0cf4729.png">

**Comment by azzhu** [comment]
Hi, this is a bug of opencv😂, and opencv is a mudule that used in easyflytracker🤣.
Bug link: https://github.com/opencv/opencv/issues?q=Segmentation+Fault
![image](https://user-images.githubusercontent.com/17442325/210135721-d7c44415-9248-4025-ab4d-f4548364cd20.png)

So, I suggest:
1. Upgrade opencv to the latest version;
    python -m pip install --upgrade opencv-python
2. Try the video again in other formats;
3. Or, share your video to me, I try it in my computer.

Thanks!
Good luck!
😊

**Comment by mmit2928** [comment]
I updated opencv and it is working now. Thank you!
